[[redirects]]
  from = "/event/:path"
  to = "https://gallery-prerender.netlify.app/.netlify/functions/render/:path/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false