[[redirects]]
  from = "/event/:path/"
  to = "http://localhost:8888/.netlify/functions/render/:path/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true