[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions/"

[[redirects]]
  from = '/event/*'
  to = 'https://gallery-prerender.netlify.app/.netlify/functions/render'
  status = 200