[[redirects]]
  from = "/event/*"
  to = "https://gallery-prerender.netlify.app/.netlify/functions/render/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/render/*"
  to = "https://www.google.com.ar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false